import numpy as np

def l2_normalize(X: np.ndarray): ...
def dist_range(metric: str = ..., normalize: bool = ...): ...
def pdist(fX, metric: str = ..., **kwargs): ...
def cdist(fX_trn, fX_tst, metric: str = ..., **kwargs): ...
def to_condensed(n, i, j): ...
def to_squared(n, k): ...
