from typing import Iterable, Iterator, List, Optional, Set, Union

def pairwise(iterable: Iterable): ...
def string_generator(skip: Optional[Union[List, Set]] = ...) -> Iterator[str]: ...
def int_generator() -> Iterator[int]: ...
