from typing import Iterable, Iterator, Optional, Union

def pairwise(iterable: Iterable): ...
def string_generator(skip: Optional[Union[list, set]] = ...) -> Iterator[str]: ...
def int_generator() -> Iterator[int]: ...
