from pyannote.core import Segment
from typing import Iterable, Iterator, Optional

def random_segment(segments: Iterable[Segment], weighted: bool = ...) -> Iterator[Segment]: ...
def random_subsegment(segment: Segment, duration: float, min_duration: Optional[float] = ...) -> Iterator[Segment]: ...
