from _typeshed import Incomplete

def fuse_linear(spec, layers) -> None: ...
def permute_for_sliced_rotary(
    weight, num_heads, rotary_dim: Incomplete | None = ...
): ...
def smooth_activation(layer_norm, linear, activation_scales) -> None: ...
def raise_unsupported(reasons) -> None: ...

class ConfigurationChecker:
    def __init__(self) -> None: ...
    def __call__(self, assert_condition, error_message) -> None: ...
    def validate(self) -> None: ...
