import torch

class ReproducibilityError(Exception): ...
class ReproducibilityWarning(UserWarning): ...

def raise_reproducibility(device: torch.device): ...
def warn_reproducibility(device: torch.device): ...
def fix_reproducibility(device: torch.device): ...
