from .classification import ClosestAssignment as ClosestAssignment
from .clustering import AffinityPropagationClustering as AffinityPropagationClustering, HierarchicalAgglomerativeClustering as HierarchicalAgglomerativeClustering
