from .protocol import Preprocessor as Preprocessor, Preprocessors as Preprocessors, Protocol as Protocol, ProtocolFile as ProtocolFile, Subset as Subset
from pyannote.core import Annotation as Annotation, Timeline as Timeline
from typing import Dict, Optional

def crop_annotated(current_file: ProtocolFile, existing_preprocessor: Optional[Preprocessor] = ...) -> Timeline: ...
def crop_annotation(current_file: ProtocolFile, existing_preprocessor: Optional[Preprocessor] = ...) -> Annotation: ...

class SegmentationProtocol(Protocol):
    def __init__(self, preprocessors: Optional[Preprocessors] = ...) -> None: ...
    def stats(self, subset: Subset = ...) -> Dict: ...
