from .protocol import LEGACY_SUBSET_MAPPING as LEGACY_SUBSET_MAPPING, Subset as Subset
from .speaker_diarization import SpeakerDiarizationProtocol as SpeakerDiarizationProtocol
from typing import Dict, Iterator

class SpeakerVerificationProtocol(SpeakerDiarizationProtocol):
    def subset_trial_helper(self, subset: Subset) -> Iterator[Dict]: ...
    def train_trial_iter(self) -> Iterator[Dict]: ...
    def development_trial_iter(self) -> Iterator[Dict]: ...
    def test_trial_iter(self) -> Iterator[Dict]: ...
    def train_trial(self) -> Iterator[Dict]: ...
    def development_trial(self) -> Iterator[Dict]: ...
    def test_trial(self) -> Iterator[Dict]: ...
