from typing import Iterator

from .protocol import LEGACY_SUBSET_MAPPING as LEGACY_SUBSET_MAPPING
from .protocol import Subset as Subset
from .speaker_diarization import (
    SpeakerDiarizationProtocol as SpeakerDiarizationProtocol,
)

class SpeakerVerificationProtocol(SpeakerDiarizationProtocol):
    def subset_trial_helper(self, subset: Subset) -> Iterator[dict]: ...
    def train_trial_iter(self) -> Iterator[dict]: ...
    def development_trial_iter(self) -> Iterator[dict]: ...
    def test_trial_iter(self) -> Iterator[dict]: ...
    def train_trial(self) -> Iterator[dict]: ...
    def development_trial(self) -> Iterator[dict]: ...
    def test_trial(self) -> Iterator[dict]: ...
