from pyannote.core import Annotation, Timeline
from typing import Union

class SegmentationErrorAnalysis:
    def __init__(self) -> None: ...
    def __call__(self, reference: Union[Timeline, Annotation], hypothesis: Union[Timeline, Annotation]) -> Annotation: ...
